DROP database if exists company_db;
CREATE database company_db;

USE company_db;

CREATE TABLE departments
(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR (64) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE roles
(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
title VARCHAR (64) NOT NULL,
salary DECIMAL,
department_id INT UNSIGNED NOT NULL FOREIGN KEY REFERENCES (departments),
PRIMARY KEY (id)
);

CREATE TABLE employees
(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
first_name VARCHAR (64) NOT NULL,
last_name VARCHAR (64) NOT NULL,
role_id INT NOT NULL UNSIGNED,
manager_id INT NULL UNSIGNED,
CONSTRAINT fk_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL
PRIMARY KEY(id)
);

